### ISSUE TITLE
P2P code review 16-9-2021

### ISSUE THREAD

**Issue by DyaryRaoof** [Takhmina175/awesome_books#3]

**Comment by jonathastavares** [comment]
I think you can display books title and author in the same line like a flexbox, it would be easier to read, also add some labels to what is the title and what is the author after updating the list.

**Comment by DyaryRaoof** [comment]
Your project looks great so far. the only thing I can think of is that you have some comments in the code. please try and remove that before your review.

**Comment by Qoosim** [comment]
Thanks a lot, buddies. My partner and I have taken care of the suggested observations.
